export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  openAiApiKey: process.env.OPENAI_API_KEY ?? "",
  openAiModel: process.env.OPENAI_MODEL ?? "gpt-4.1-mini",
  nvidiaApiKey: process.env.NVIDIA_API_KEY ?? "",
  nvidiaNimBaseUrl: process.env.NVIDIA_NIM_BASE_URL ?? "https://integrate.api.nvidia.com/v1",
  nvidiaNimModel: process.env.NVIDIA_NIM_MODEL ?? "",
  metaHorizonAppId: process.env.META_HORIZON_APP_ID ?? "",
  appleAppId: process.env.APPLE_APP_ID ?? "",
  appleAssociatedDomain: process.env.APPLE_ASSOCIATED_DOMAIN ?? "",
  microsoftTenantId: process.env.MICROSOFT_TENANT_ID ?? "",
  microsoftClientId: process.env.MICROSOFT_CLIENT_ID ?? "",
  microsoftClientSecret: process.env.MICROSOFT_CLIENT_SECRET ?? "",
};
