CREATE TABLE `ems_billing` (
	`id` int AUTO_INCREMENT NOT NULL,
	`billNumber` varchar(20) NOT NULL,
	`incidentId` int NOT NULL,
	`incidentNumber` varchar(24) NOT NULL,
	`patientName` varchar(128),
	`billingType` enum('insurance','medicare','medicaid','self_pay','government','workers_comp') NOT NULL,
	`insurerName` varchar(128),
	`policyNumber` varchar(64),
	`groupNumber` varchar(64),
	`icd10Code` varchar(16),
	`transportCode` varchar(16),
	`billedAmountCents` int NOT NULL DEFAULT 0,
	`allowedAmountCents` int DEFAULT 0,
	`paidAmountCents` int DEFAULT 0,
	`patientResponsibilityCents` int DEFAULT 0,
	`status` enum('draft','submitted','pending','approved','denied','appealed','paid','written_off') NOT NULL DEFAULT 'draft',
	`denialCode` varchar(32),
	`denialReason` text,
	`submittedAt` timestamp,
	`paidAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ems_billing_id` PRIMARY KEY(`id`),
	CONSTRAINT `ems_billing_billNumber_unique` UNIQUE(`billNumber`)
);
--> statement-breakpoint
CREATE TABLE `ems_compliance` (
	`id` int AUTO_INCREMENT NOT NULL,
	`complianceType` enum('nemsis','nfirs','pcr','certification','equipment_check','training','hipaa','cms_audit') NOT NULL,
	`title` varchar(256) NOT NULL,
	`description` text,
	`status` enum('compliant','due','overdue','in_review','waived') NOT NULL DEFAULT 'due',
	`incidentId` int,
	`assignedTo` varchar(128),
	`dueDate` timestamp,
	`completedAt` timestamp,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ems_compliance_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ems_incidents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`incidentNumber` varchar(24) NOT NULL,
	`incidentType` enum('medical','fire','mva','hazmat','rescue','mutual_aid','public_assist','false_alarm') NOT NULL,
	`priority` enum('P1','P2','P3','P4') NOT NULL DEFAULT 'P2',
	`status` enum('pending','dispatched','on_scene','transporting','resolved','cancelled') NOT NULL DEFAULT 'pending',
	`address` varchar(256) NOT NULL,
	`city` varchar(64) NOT NULL DEFAULT 'West Liberty',
	`state` varchar(2) NOT NULL DEFAULT 'IA',
	`lat` varchar(20),
	`lng` varchar(20),
	`patientName` varchar(128),
	`patientDob` varchar(16),
	`patientInsurance` varchar(128),
	`dispatchedUnits` text,
	`leadCrew` varchar(128),
	`narrative` text,
	`nemsisCode` varchar(16),
	`nfirsCode` varchar(16),
	`hospital` varchar(128),
	`dispatchedAt` timestamp,
	`onSceneAt` timestamp,
	`transportedAt` timestamp,
	`resolvedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ems_incidents_id` PRIMARY KEY(`id`),
	CONSTRAINT `ems_incidents_incidentNumber_unique` UNIQUE(`incidentNumber`)
);
--> statement-breakpoint
CREATE TABLE `ems_units` (
	`id` int AUTO_INCREMENT NOT NULL,
	`unitId` varchar(16) NOT NULL,
	`unitType` enum('ambulance','fire_engine','ladder','command','rescue','hazmat','drone','radio_tower') NOT NULL,
	`callSign` varchar(32) NOT NULL,
	`status` enum('available','dispatched','on_scene','transporting','at_hospital','returning','out_of_service','standby') NOT NULL DEFAULT 'available',
	`crew` text,
	`lat` varchar(20),
	`lng` varchar(20),
	`speedMph` int DEFAULT 0,
	`heading` int DEFAULT 0,
	`currentIncidentId` int,
	`vehicle` varchar(128),
	`plate` varchar(16),
	`lastPingTs` bigint,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ems_units_id` PRIMARY KEY(`id`),
	CONSTRAINT `ems_units_unitId_unique` UNIQUE(`unitId`)
);
