/* 
 * DOGE-LANDSCAPER Data Store
 * Iowa ZIP 52776 (Wilton, Iowa) — USDA Hardiness Zone 5b
 * Cool-season grasses: Kentucky Bluegrass, Tall Fescue, Perennial Ryegrass
 */

export const ROBOT_PERSONA_DEFAULT = {
  name: "Chip McHaymaker",
  nickname: "The Corn Belt Cultivator",
  tagline: "Ain't no dandelion safe in Wilton, Iowa — not on my watch!",
  hat: "John Deere Green Cap",
  outfit: "Denim Overalls",
  shirt: "Plaid Flannel",
  boots: "Steel-Toe Work Boots",
  accessory: "Scotts Turf Builder Bag",
  mood: "😄 Ready to Rumble",
  hatColor: "#2d5a1b",
  outfitColor: "#4a6fa5",
  shirtColor: "#8b4513",
  skinTone: "#c0c0c0",
  eyeColor: "#00bfff",
  catchphrase: "By golly, that lawn ain't gonna mow itself!",
  bio: "Born and raised in the Corn Belt, Chip knows Iowa soil like the back of his titanium hand. Hardiness Zone 5b? More like his comfort zone. He's got opinions about fertilizer schedules and he's not afraid to share 'em.",
};

export type RobotPersona = typeof ROBOT_PERSONA_DEFAULT;

export const IOWA_LAWN_CALENDAR = [
  {
    month: "March",
    tasks: ["Soil temp check (>50°F for pre-emergent)", "Rake winter debris", "Sharpen mower blades", "Test soil pH"],
    products: ["Pre-emergent crabgrass preventer"],
    warning: "Don't mow until soil dries — compaction risk!",
    chipQuip: "March in Iowa: 'Is it spring yet?' — Chip checks soil temp 47 times.",
  },
  {
    month: "April",
    tasks: ["First mow at 2.5\"", "Apply Scotts Turf Builder Weed & Feed", "Overseed thin spots", "Edge beds"],
    products: ["Scotts Turf Builder Weed & Feed", "Grass seed blend"],
    warning: "Apply Weed & Feed when lawn is wet (dew) for best adhesion",
    chipQuip: "April showers bring dandelions. Chip brings Scotts.",
  },
  {
    month: "May",
    tasks: ["Mow weekly at 3\"", "Deep water 1\" per week", "Watch for grubs", "Fertilize if needed"],
    products: ["Grub control", "Liquid fertilizer"],
    warning: "Avoid fertilizing in heat — wait for temps below 85°F",
    chipQuip: "May: Chip's favorite month. Everything's green and he gets the credit.",
  },
  {
    month: "June",
    tasks: ["Raise mower to 3.5\"", "Water early morning", "Spot-treat weeds", "Check irrigation"],
    products: ["Spot weed killer", "Hose-end sprayer"],
    warning: "High temps incoming — raise mow height to reduce stress",
    chipQuip: "June heat? Chip just turns up his cooling fans.",
  },
  {
    month: "July",
    tasks: ["Mow at 4\" in heat", "Water 1-1.5\" per week", "Skip fertilizer", "Monitor for chinch bugs"],
    products: ["Insect control spray"],
    warning: "Lawn may go dormant — that's OK! Don't overwater dormant grass",
    chipQuip: "July in Iowa: 95°F and 90% humidity. Chip's sensors are sweating.",
  },
  {
    month: "August",
    tasks: ["Continue watering", "Prep for fall seeding", "Aerate compacted areas", "Dethatch if needed"],
    products: ["Core aerator rental", "Dethatcher"],
    warning: "Best time to plan fall renovation — mark thin spots now",
    chipQuip: "August: Chip starts his fall planning spreadsheet. It's 47 tabs.",
  },
  {
    month: "September",
    tasks: ["Aerate and overseed", "Apply fall fertilizer", "Mow back to 3\"", "Rake leaves promptly"],
    products: ["Scotts Turf Builder Fall Fertilizer", "Grass seed", "Core aerator"],
    warning: "BEST MONTH for Iowa lawn work — cool temps, good moisture",
    chipQuip: "September is Chip's Super Bowl. He trains all year for this.",
  },
  {
    month: "October",
    tasks: ["Final fertilizer application", "Keep mowing until dormant", "Winterize irrigation", "Mulch leaves"],
    products: ["Winterizer fertilizer"],
    warning: "Apply winterizer before first hard frost (usually mid-October in Wilton)",
    chipQuip: "October: Chip's doing his victory lap before hibernation.",
  },
  {
    month: "November",
    tasks: ["Final mow at 2.5\"", "Store equipment", "Clean mower deck", "Drain fuel"],
    products: ["Fuel stabilizer", "Equipment oil"],
    warning: "Final mow height: 2.5\" prevents snow mold",
    chipQuip: "November: Chip goes into low-power mode. Dreaming of spring.",
  },
  {
    month: "December",
    tasks: ["Equipment maintenance", "Order spring supplies", "Review lawn map", "Plan improvements"],
    products: ["Pre-order Scotts products"],
    warning: "Order Scotts Weed & Feed early — it sells out in Wilton by March!",
    chipQuip: "December: Chip watches Iowa Hawkeyes football and dreams of dandelion-free lawns.",
  },
  {
    month: "January",
    tasks: ["Stay off frozen lawn", "Plan spring layout", "Research new grass varieties", "Sharpen tools"],
    products: [],
    warning: "Never walk on frozen grass — crowns are fragile!",
    chipQuip: "January: Chip's charging. Don't disturb.",
  },
  {
    month: "February",
    tasks: ["Soil test", "Order seeds", "Service equipment", "Plan irrigation"],
    products: ["Soil test kit", "Seed catalog"],
    warning: "Soil test now so you have results before spring rush",
    chipQuip: "February: Chip's pre-season training. Watching lawn care YouTube.",
  },
];

export const PRODUCTS_INVENTORY = [
  {
    id: "scotts-weed-feed",
    name: "Scotts Turf Builder Weed & Feed",
    brand: "Scotts",
    type: "Fertilizer + Herbicide",
    coverage: "12,000 sq ft",
    weight: "28.7 lbs",
    npk: "28-0-3",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/116029439/cao3qXUUr9zrMdetSxxjdj/IMG_0730_6a1079d9.jpeg",
    inStock: true,
    quantity: 1,
    notes: "WeedGrip Technology — clears dandelions and clover. Apply when lawn is wet.",
    bestTime: "April–May, when soil temp 50-90°F",
    oversprayRisk: "HIGH near flower beds — use shield",
  },
  {
    id: "scotts-fall",
    name: "Scotts Turf Builder Fall Fertilizer",
    brand: "Scotts",
    type: "Fertilizer",
    coverage: "15,000 sq ft",
    weight: "32 lbs",
    npk: "32-0-10",
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400",
    inStock: true,
    quantity: 0,
    notes: "High potassium for winter hardiness. Apply Sept-Oct.",
    bestTime: "September–October",
    oversprayRisk: "LOW",
  },
  {
    id: "roundup-weed",
    name: "Roundup Weed & Grass Killer",
    brand: "Roundup",
    type: "Herbicide",
    coverage: "N/A (spot treatment)",
    weight: "1 gallon",
    npk: "N/A",
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=400",
    inStock: false,
    quantity: 0,
    notes: "Spot treatment only. Keep away from desirable plants.",
    bestTime: "When weeds are actively growing",
    oversprayRisk: "CRITICAL — kills everything",
  },
];

export const WEATHER_HOURLY = [
  { time: "6:00 AM", temp: 52, condition: "Clear", wind: 5, humidity: 72, sprayOk: true, icon: "☀️" },
  { time: "7:00 AM", temp: 54, condition: "Clear", wind: 6, humidity: 70, sprayOk: true, icon: "☀️" },
  { time: "8:00 AM", temp: 58, condition: "Partly Cloudy", wind: 8, humidity: 68, sprayOk: true, icon: "⛅" },
  { time: "9:00 AM", temp: 63, condition: "Partly Cloudy", wind: 10, humidity: 65, sprayOk: true, icon: "⛅" },
  { time: "10:00 AM", temp: 67, condition: "Partly Cloudy", wind: 12, humidity: 62, sprayOk: true, icon: "⛅" },
  { time: "11:00 AM", temp: 71, condition: "Mostly Cloudy", wind: 14, humidity: 60, sprayOk: false, icon: "🌥️" },
  { time: "12:00 PM", temp: 74, condition: "Mostly Cloudy", wind: 16, humidity: 58, sprayOk: false, icon: "🌥️" },
  { time: "1:00 PM", temp: 76, condition: "Partly Cloudy", wind: 15, humidity: 57, sprayOk: false, icon: "⛅" },
  { time: "2:00 PM", temp: 77, condition: "Partly Cloudy", wind: 13, humidity: 56, sprayOk: true, icon: "⛅" },
  { time: "3:00 PM", temp: 75, condition: "Partly Cloudy", wind: 11, humidity: 58, sprayOk: true, icon: "⛅" },
  { time: "4:00 PM", temp: 72, condition: "Clear", wind: 9, humidity: 60, sprayOk: true, icon: "☀️" },
  { time: "5:00 PM", temp: 68, condition: "Clear", wind: 7, humidity: 63, sprayOk: true, icon: "☀️" },
  { time: "6:00 PM", temp: 64, condition: "Clear", wind: 6, humidity: 66, sprayOk: true, icon: "🌅" },
  { time: "7:00 PM", temp: 60, condition: "Clear", wind: 5, humidity: 68, sprayOk: true, icon: "🌅" },
];

export const MISSION_TASKS = [
  {
    id: "morning-survey",
    time: "6:30 AM",
    name: "Morning Yard Survey",
    description: "LiDAR scan full property, identify overnight changes, check for animal activity",
    zone: "Full Property",
    duration: "15 min",
    priority: "high",
    status: "completed",
    tools: ["LiDAR", "Camera", "AI Vision"],
    chipNote: "Chip found 3 new dandelions overnight. He's taking it personally.",
  },
  {
    id: "weed-feed-apply",
    time: "8:00 AM",
    name: "Apply Scotts Weed & Feed",
    description: "Apply to lawn zones A & B. Avoid flower beds, swing set area, and garden borders. Minimum overspray protocol active.",
    zone: "Lawn A + B",
    duration: "45 min",
    priority: "high",
    status: "in-progress",
    tools: ["Spreader", "Shield Guard", "Wind Sensor"],
    chipNote: "Wind at 8mph — acceptable. Chip's got his shield guard ready.",
  },
  {
    id: "mow-main",
    time: "10:00 AM",
    name: "Mow Main Lawn",
    description: "Mow at 3\" height. Pattern: diagonal stripes for visual appeal. Avoid oak tree root zone (6ft radius).",
    zone: "Main Lawn",
    duration: "60 min",
    priority: "medium",
    status: "pending",
    tools: ["Mower", "Edge Trimmer"],
    chipNote: "Chip insists on diagonal stripes. Says it adds 15% curb appeal.",
  },
  {
    id: "edge-beds",
    time: "11:30 AM",
    name: "Edge Garden Beds",
    description: "Clean edge along fence line and garden borders. Collect clippings.",
    zone: "Perimeter",
    duration: "30 min",
    priority: "low",
    status: "pending",
    tools: ["Edge Trimmer", "Blower"],
    chipNote: "Crisp edges are Chip's love language.",
  },
  {
    id: "afternoon-water",
    time: "2:00 PM",
    name: "Targeted Irrigation",
    description: "Water thin spots and recently seeded areas. 0.5\" application. Skip if rain forecast within 24hrs.",
    zone: "Thin Spots",
    duration: "20 min",
    priority: "medium",
    status: "pending",
    tools: ["Irrigation System", "Moisture Sensor"],
    chipNote: "Chip checks soil moisture before watering. He's not a wasteful robot.",
  },
  {
    id: "evening-report",
    time: "6:00 PM",
    name: "Evening Status Report",
    description: "Generate daily lawn health report, update LiDAR map, log completed tasks, set tomorrow's mission.",
    zone: "Command Center",
    duration: "10 min",
    priority: "high",
    status: "pending",
    tools: ["AI Analysis", "Camera", "Report Generator"],
    chipNote: "Chip's favorite part of the day. He gives himself a gold star.",
  },
];

export const TRAINING_SCENARIOS = [
  {
    id: "scenario-1",
    title: "The Great Dandelion Invasion",
    difficulty: "Easy",
    description: "It's April in Wilton. You've spotted 47 dandelions in the front lawn. Wind is 8mph from the west. You have Scotts Weed & Feed. What's your move?",
    image: "https://d2xsxph8kpxj0f.cloudfront.net/116029439/cao3qXUUr9zrMdetSxxjdj/IMG_0731_9eed3482.jpeg",
    options: [
      { text: "Apply Weed & Feed immediately — the dandelions must die!", correct: false, feedback: "Not quite! Check wind speed first. 8mph is borderline — apply early morning when wind is calmer, and use a shield near flower beds." },
      { text: "Wait for morning dew, then apply Weed & Feed with shield guard near beds", correct: true, feedback: "Correct! Morning dew helps granules stick to weed leaves. Shield guard prevents overspray to flower beds. Chip approves!" },
      { text: "Spot spray each dandelion with Roundup", correct: false, feedback: "Roundup kills everything — including your grass! Use Weed & Feed for lawn-safe dandelion control." },
      { text: "Hand-pull all 47 dandelions", correct: false, feedback: "Technically correct but inefficient. Chip would need 3 hours and a chiropractor. Use the right tool for the job!" },
    ],
    chipTip: "Dandelions in Iowa peak in April-May. Scotts Weed & Feed with WeedGrip Technology is your best friend. Apply when lawn is wet, wind under 10mph.",
  },
  {
    id: "scenario-2",
    title: "The Drought Decision",
    difficulty: "Medium",
    description: "It's July 15th. Temp is 95°F. Your lawn has gone dormant (brown). Your neighbor is watering daily. What do you do?",
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600",
    options: [
      { text: "Water daily like your neighbor — green lawn = happy lawn", correct: false, feedback: "Overwatering dormant grass can cause fungal disease and wastes water. Dormancy is a survival mechanism!" },
      { text: "Apply fertilizer to wake it up", correct: false, feedback: "NEVER fertilize dormant or heat-stressed grass. You'll burn the crowns and potentially kill the lawn." },
      { text: "Water 1\" per week to maintain dormancy without killing crowns", correct: true, feedback: "Correct! 1\" per week keeps crowns alive during dormancy. Grass will green up when temps drop. Chip nods approvingly." },
      { text: "Do nothing — let it die and reseed in fall", correct: false, feedback: "Letting it fully die is risky. A little water maintains the crowns. Full reseeding is expensive and unnecessary." },
    ],
    chipTip: "Iowa summer dormancy is normal for cool-season grasses. Maintain with 1\"/week. Never fertilize stressed grass. September is your reset button.",
  },
  {
    id: "scenario-3",
    title: "The Fall Renovation",
    difficulty: "Hard",
    description: "It's September 5th. Your lawn has 40% bare spots, compacted soil, and thick thatch. You have 6 weeks before first frost. Prioritize your actions.",
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600",
    options: [
      { text: "Overseed immediately, then aerate, then fertilize", correct: false, feedback: "Wrong order! Aerate first — it creates seed-to-soil contact. Then overseed into the holes, then fertilize." },
      { text: "Aerate → Overseed → Apply starter fertilizer → Water daily", correct: true, feedback: "Perfect sequence! Aeration first breaks compaction and creates seed pockets. Starter fertilizer feeds new seedlings. Chip gives a standing ovation." },
      { text: "Apply Weed & Feed, then overseed in 4 weeks", correct: false, feedback: "Weed & Feed contains herbicide that prevents seed germination! Never apply before overseeding." },
      { text: "Wait until spring — fall is too late", correct: false, feedback: "September is actually the BEST time for Iowa lawn renovation! Cool temps and fall rains are perfect for germination." },
    ],
    chipTip: "September 1-15 is the golden window for Iowa lawn renovation. Soil is warm, air is cool, rain is coming. Aerate → Overseed → Starter Fert → Water. This is Chip's Super Bowl.",
  },
];

export const AI_RECOMMENDATIONS = [
  {
    id: "rec-1",
    priority: "urgent",
    category: "Weed Control",
    title: "Dandelion Density: HIGH",
    description: "AI Vision detected 23 dandelions in Zone A (main lawn). Recommend Scotts Turf Builder Weed & Feed application this week. Optimal window: Tomorrow 7-9 AM (dew present, wind 5mph).",
    action: "Schedule Weed & Feed Application",
    confidence: 94,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/116029439/cao3qXUUr9zrMdetSxxjdj/IMG_0730_6a1079d9.jpeg",
  },
  {
    id: "rec-2",
    priority: "high",
    category: "Soil Health",
    title: "Thin Spots Near Oak Tree",
    description: "LiDAR + camera analysis shows sparse grass coverage within 8ft of oak tree base (visible in yard scan). Root competition and shade stress detected. Scilla siberica (blue squill) naturalized throughout — a positive sign. Recommend shade-tolerant Fine Fescue blend and compost topdressing.",
    action: "Order Fine Fescue Seed + Compost",
    confidence: 87,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/116029439/cao3qXUUr9zrMdetSxxjdj/IMG_0731_9eed3482.jpeg",
  },
  {
    id: "rec-3",
    priority: "medium",
    category: "Irrigation",
    title: "Soil Moisture: Below Optimal",
    description: "Moisture sensors indicate 28% soil moisture (optimal: 40-60%). No rain forecast for 5 days. Recommend 0.75\" irrigation application in early morning to avoid evaporation loss.",
    action: "Schedule Morning Irrigation",
    confidence: 91,
    image: null,
  },
  {
    id: "rec-4",
    priority: "low",
    category: "Enhancement",
    title: "Scilla Bulbs: Naturalize Opportunity",
    description: "Blue scilla (Scilla siberica) detected throughout lawn — these are beneficial spring ephemerals. Consider expanding naturalized bulb areas near fence line for low-maintenance color.",
    action: "Order Scilla Bulbs for Fall Planting",
    confidence: 78,
    image: "https://d2xsxph8kpxj0f.cloudfront.net/116029439/cao3qXUUr9zrMdetSxxjdj/IMG_0731_9eed3482.jpeg",
  },
];

export const DEBUG_DATA = {
  system: {
    "CPU": "Nvidia Jetson Orin NX — 16GB",
    "GPU": "1024-core Ampere",
    "OS": "JetPack 6.1 / Ubuntu 22.04",
    "RAM": "16 GB LPDDR5",
    "Storage": "256 GB NVMe",
    "Uptime": "14h 23m 11s",
    "Temp": "52°C",
    "Power": "18.4W",
  },
  sensors: {
    "LiDAR": "Ouster OS1-32 — ACTIVE",
    "Camera (POV)": "Sony IMX477 4K — STREAMING",
    "Continuity Camera": "iPhone 16 Pro — CONNECTED",
    "IMU": "BNO085 — CALIBRATED",
    "GPS": "u-blox ZED-F9P — 2.1cm accuracy",
    "Moisture Sensor": "Capacitive x4 — ACTIVE",
    "Wind Sensor": "Davis 6410 — 8.2 mph NW",
  },
  network: {
    "WiFi": "5GHz — -42 dBm",
    "Latency": "12ms",
    "Bandwidth": "↑ 2.1 Mbps / ↓ 8.4 Mbps",
    "Continuity": "iOS 27 — PAIRED",
    "visionOS": "Apple Vision Pro — STANDBY",
    "tvOS": "Apple TV 4K — MIRRORING",
  },
  ai: {
    "Vision Model": "YOLOv9 + SAM2",
    "LLM": "Llama 3.2 Vision (local)",
    "Inference": "TensorRT 10 — 47ms",
    "Objects Detected": "12",
    "Weeds Identified": "23 dandelions, 4 clover patches",
    "Confidence": "94.2%",
  },
};
