import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, BellRing, CheckCircle2, ClipboardCheck, ClipboardList, Download, Printer, RefreshCw, Sparkles, Truck, Users } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

function Metric({ icon: Icon, label, value, color }: { icon: any; label: string; value: string | number; color: string }) { return <Card className="border-slate-200 shadow-sm"><CardContent className="flex items-center gap-3 p-4"><span className="rounded-xl p-2.5" style={{ color, backgroundColor: `${color}14` }}><Icon className="h-5 w-5" /></span><div><p className="text-[10px] font-bold tracking-[0.13em] text-slate-500 uppercase">{label}</p><p className="mt-1 text-xl font-extrabold text-slate-900">{value}</p></div></CardContent></Card>; }
function Priority({ value }: { value: string }) { const styles: Record<string, string> = { critical: "bg-red-100 text-red-700", high: "bg-orange-100 text-orange-700", normal: "bg-blue-100 text-blue-700", low: "bg-slate-100 text-slate-600" }; return <span className={`rounded-full px-2 py-1 text-[10px] font-bold capitalize ${styles[value] || styles.normal}`}>{value}</span>; }

export default function DailyBrief() {
  const dashboard = trpc.aac.dashboard.useQuery(); const actions = trpc.aac.actions.useQuery(); const utils = trpc.useUtils();
  const [brief, setBrief] = useState<ReturnType<typeof trpc.aac.dailyBrief.useMutation>["data"]>();
  const generate = trpc.aac.dailyBrief.useMutation({ onSuccess: data => { setBrief(data); utils.aac.actions.invalidate(); utils.aac.dashboard.invalidate(); toast.success(data.notificationDelivered ? "Brief generated and sent to the owner." : "Brief generated. Owner notification will retry when service is available."); }, onError: () => toast.error("Brief generation could not be completed. Please retry.") });
  const saveAction = trpc.aac.saveAction.useMutation({ onSuccess: () => { utils.aac.actions.invalidate(); utils.aac.dashboard.invalidate(); toast.success("Action item updated."); }, onError: () => toast.error("Action update could not be saved.") });
  const download = () => { if (!brief) return; const file = new Blob([`# ${brief.title}\n\n${brief.content}`], { type: "text/markdown" }); const url = URL.createObjectURL(file); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `aac-daily-brief-${new Date().toISOString().slice(0, 10)}.md`; anchor.click(); URL.revokeObjectURL(url); };
  const data = dashboard.data; const openActions = (actions.data ?? []).filter((action: any) => action.status !== "complete");
  return <DashboardLayout><><div className="mx-auto max-w-6xl space-y-6 print:hidden">
    <section className="overflow-hidden rounded-3xl bg-gradient-to-br from-orange-500 to-orange-600 p-6 text-white shadow-xl shadow-orange-200 sm:p-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div className="flex items-center gap-2 text-orange-100"><Sparkles className="h-4 w-4" /><span className="text-xs font-bold tracking-[0.16em] uppercase">AAC intelligence workspace</span></div><h1 className="mt-3 text-3xl font-extrabold tracking-tight">Daily Operations Brief</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-orange-50">Synthesize today’s pours, readiness, crew coverage, materials, active alerts, and West Liberty conditions into a meeting-ready handoff.</p></div><div className="flex flex-wrap gap-2"><Button onClick={() => generate.mutate()} disabled={generate.isPending} className="bg-slate-950 text-white hover:bg-slate-900"><RefreshCw className={`mr-2 h-4 w-4 ${generate.isPending ? "animate-spin" : ""}`} />{generate.isPending ? "Building brief" : "Generate brief"}</Button>{brief && <><Button onClick={download} variant="outline" className="border-white/35 bg-white/10 text-white hover:bg-white/20 hover:text-white"><Download className="mr-2 h-4 w-4" />Download</Button><Button onClick={() => window.print()} variant="outline" className="border-white/35 bg-white/10 text-white hover:bg-white/20 hover:text-white"><Printer className="mr-2 h-4 w-4" />Print handoff</Button></>}</div></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={ClipboardList} label="Active pours" value={data ? `${data.jobSites.filter((site: any) => site.status === "active").length} sites` : "—"} color="#f97316" /><Metric icon={Truck} label="Fleet ready" value={data ? `${data.fleet.filter((unit: any) => unit.status === "operational").length}/${data.fleet.length}` : "—"} color="#059669" /><Metric icon={Users} label="Crew assigned" value={data ? data.crew.filter((person: any) => person.availability === "assigned").length : "—"} color="#2563eb" /><Metric icon={AlertTriangle} label="Open actions" value={openActions.length} color="#dc2626" /></section>
    <section className="grid gap-6 lg:grid-cols-[1.5fr_1fr]"><Card className="border-slate-200 shadow-sm print:border-none print:shadow-none"><CardContent className="p-0">{brief ? <div><div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-5"><div><p className="text-lg font-bold text-slate-900">{brief.title}</p><p className="mt-1 text-xs text-slate-500">Generated {new Date(brief.generatedAt).toLocaleString()} · {brief.notificationDelivered ? "Owner notification delivered" : "Notification delivery pending"}</p></div><Badge variant={brief.notificationDelivered ? "default" : "secondary"} className={brief.notificationDelivered ? "bg-emerald-600" : ""}>{brief.notificationDelivered ? <><CheckCircle2 className="mr-1 h-3 w-3" />Delivered</> : <><BellRing className="mr-1 h-3 w-3" />Pending</>}</Badge></div><article className="whitespace-pre-wrap p-6 font-sans text-sm leading-7 text-slate-700">{brief.content}</article></div> : <div className="flex min-h-[390px] flex-col items-center justify-center p-8 text-center"><div className="rounded-2xl bg-orange-50 p-4 text-orange-600"><ClipboardList className="h-8 w-8" /></div><h2 className="mt-5 text-lg font-bold text-slate-900">Your meeting-ready brief starts here</h2><p className="mt-2 max-w-md text-sm leading-6 text-slate-500">Generate a structured, downloadable report built from current operating data. The workspace retains a reliable fallback if AI service is temporarily unavailable.</p><Button onClick={() => generate.mutate()} disabled={generate.isPending} className="mt-6 bg-orange-500 hover:bg-orange-600">{generate.isPending ? "Generating…" : "Generate morning brief"}</Button></div>}</CardContent></Card>
      <div className="space-y-4"><Card className="border-slate-200 shadow-sm"><CardContent className="p-5"><div className="flex items-center justify-between"><div><p className="text-sm font-bold text-slate-900">Action tracker</p><p className="mt-1 text-xs text-slate-500">Assign, follow, and close morning commitments.</p></div><ClipboardCheck className="h-5 w-5 text-orange-500" /></div><div className="mt-4 space-y-3">{openActions.slice(0,5).map((action: any) => <div key={action.id || action.title} className="rounded-xl bg-slate-50 p-3"><div className="flex items-start justify-between gap-2"><p className="text-xs font-bold leading-5 text-slate-800">{action.title}</p><Priority value={action.priority} /></div><p className="mt-1 text-[11px] text-slate-500">{action.owner || "Unassigned"} · {action.dueLabel || "No due time"}</p><div className="mt-3 flex gap-2"><Button size="sm" variant="outline" className="h-7 border-slate-200 px-2 text-[10px]" disabled={saveAction.isPending} onClick={() => saveAction.mutate({ ...action, status: "in_progress" })}>Start</Button><Button size="sm" className="h-7 bg-emerald-600 px-2 text-[10px] hover:bg-emerald-700" disabled={saveAction.isPending} onClick={() => saveAction.mutate({ ...action, status: "complete" })}>Complete</Button></div></div>)}{!openActions.length && <p className="rounded-xl bg-emerald-50 p-3 text-xs text-emerald-700">No open action items. The shift handoff is clear.</p>}</div></CardContent></Card><Card className="border-orange-100 bg-orange-50/50 shadow-sm"><CardContent className="p-5"><p className="text-sm font-bold text-slate-900">Morning meeting cue</p><p className="mt-2 text-sm leading-6 text-slate-600">Review the JS-001 first-load validation, confirm MT-007’s fuel stop, and close low-stock purchase requests before dispatch accelerates. The print handoff includes the generated brief and current action tracker.</p></CardContent></Card></div></section>
  </div><section className="hidden bg-white p-8 text-slate-900 print:block"><header className="border-b-4 border-orange-500 pb-5"><p className="text-xs font-bold tracking-[0.18em] text-orange-600 uppercase">All American Concrete · West Liberty, Iowa</p><h1 className="mt-2 text-3xl font-extrabold">6 AM Shift Handoff</h1><p className="mt-2 text-sm text-slate-600">{brief?.title || "Daily Operations Brief"} · Printed {new Date().toLocaleString()}</p></header><section className="mt-6 grid grid-cols-4 gap-3"><div><p className="text-[10px] font-bold uppercase text-slate-500">Active pours</p><p className="mt-1 text-xl font-extrabold">{data?.jobSites.filter((site: any) => site.status === "active").length ?? 0}</p></div><div><p className="text-[10px] font-bold uppercase text-slate-500">Fleet ready</p><p className="mt-1 text-xl font-extrabold">{data ? `${data.fleet.filter((unit: any) => unit.status === "operational").length}/${data.fleet.length}` : "—"}</p></div><div><p className="text-[10px] font-bold uppercase text-slate-500">Crew assigned</p><p className="mt-1 text-xl font-extrabold">{data?.crew.filter((person: any) => person.availability === "assigned").length ?? 0}</p></div><div><p className="text-[10px] font-bold uppercase text-slate-500">Open actions</p><p className="mt-1 text-xl font-extrabold">{openActions.length}</p></div></section><section className="mt-8"><h2 className="border-b border-slate-200 pb-2 text-lg font-bold">Operations brief</h2><article className="mt-4 whitespace-pre-wrap text-sm leading-6">{brief?.content || "Generate the Daily Operations Brief before printing the handoff."}</article></section><section className="mt-8"><h2 className="border-b border-slate-200 pb-2 text-lg font-bold">Action commitments</h2><table className="mt-4 w-full border-collapse text-left text-xs"><thead><tr className="border-b border-slate-300 text-slate-500"><th className="pb-2">Action</th><th className="pb-2">Owner</th><th className="pb-2">Priority</th><th className="pb-2">Due</th><th className="pb-2">State</th></tr></thead><tbody>{openActions.map((action: any) => <tr key={action.id || action.title} className="border-b border-slate-100"><td className="py-3 pr-4 font-semibold">{action.title}</td><td className="py-3 pr-4">{action.owner || "Unassigned"}</td><td className="py-3 pr-4 capitalize">{action.priority}</td><td className="py-3 pr-4">{action.dueLabel || "—"}</td><td className="py-3 capitalize">{action.status.replace("_", " ")}</td></tr>)}</tbody></table></section><footer className="mt-10 border-t border-slate-200 pt-3 text-[10px] text-slate-500">AAC Operations · Confirm safety, dispatch, quality control, and material actions before release.</footer></section></></DashboardLayout>;
}
