import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Fuel, Gauge, RefreshCw, ShieldAlert, Truck, Wrench } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

type Unit = any;
const statusStyles: Record<string, string> = { operational: "bg-emerald-100 text-emerald-700", maintenance: "bg-amber-100 text-amber-700", alert: "bg-red-100 text-red-700", offline: "bg-slate-100 text-slate-600" };
export default function FleetEquipment() {
  const fleetQuery = trpc.aac.fleet.useQuery(); const utils = trpc.useUtils(); const [filter, setFilter] = useState("all"); const [editing, setEditing] = useState<Unit | null>(null);
  const save = trpc.aac.saveFleetUnit.useMutation({ onSuccess: () => { toast.success("Fleet unit updated."); utils.aac.fleet.invalidate(); utils.aac.dashboard.invalidate(); setEditing(null); }, onError: () => toast.error("The unit update could not be saved.") });
  const units = useMemo(() => (fleetQuery.data ?? []).filter((unit: Unit) => filter === "all" || unit.status === filter), [fleetQuery.data, filter]);
  const all = fleetQuery.data ?? []; const count = (status: string) => all.filter((unit: Unit) => unit.status === status).length;
  return <DashboardLayout><div className="mx-auto max-w-7xl space-y-6"><section className="flex flex-col justify-between gap-5 rounded-3xl bg-slate-950 p-6 text-white sm:flex-row sm:items-end"><div><p className="font-mono text-xs tracking-[0.18em] text-orange-300 uppercase">Readiness & maintenance</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight">Fleet & Equipment</h1><p className="mt-2 text-sm text-slate-300">Operational status, active assignments, fuel readiness, and service visibility for every critical unit.</p></div><Button onClick={() => fleetQuery.refetch()} variant="outline" className="border-white/15 bg-white/5 text-white hover:bg-white/10 hover:text-white"><RefreshCw className="mr-2 h-4 w-4" />Refresh status</Button></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[{ label: "Operational", value: count("operational"), color: "text-emerald-600", icon: Truck }, { label: "Maintenance", value: count("maintenance"), color: "text-amber-600", icon: Wrench }, { label: "Attention", value: count("alert"), color: "text-red-600", icon: ShieldAlert }, { label: "Average fuel", value: all.length ? `${Math.round(all.reduce((total: number, unit: Unit) => total + unit.fuelPercent, 0) / all.length)}%` : "—", color: "text-blue-600", icon: Fuel }].map(item => <Card key={item.label} className="border-slate-200 shadow-sm"><CardContent className="flex items-center justify-between p-4"><div><p className="text-[10px] font-bold tracking-[0.13em] text-slate-500 uppercase">{item.label}</p><p className={`mt-1 text-2xl font-extrabold ${item.color}`}>{item.value}</p></div><item.icon className={`h-5 w-5 ${item.color}`} /></CardContent></Card>)}</section>
    <div className="flex flex-wrap gap-2">{["all", "operational", "maintenance", "alert", "offline"].map(option => <Button key={option} variant={filter === option ? "default" : "outline"} onClick={() => setFilter(option)} className={filter === option ? "bg-orange-500 hover:bg-orange-600" : "border-slate-200"}>{option === "all" ? `All units (${all.length})` : `${option[0].toUpperCase() + option.slice(1)} (${count(option)})`}</Button>)}</div>
    <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{fleetQuery.isLoading ? [1,2,3,4,5,6].map(i => <div key={i} className="h-72 animate-pulse rounded-2xl bg-slate-200" />) : units.map((unit: Unit) => <Card key={unit.id || unit.unitNumber} className="overflow-hidden border-slate-200 shadow-sm"><CardContent className="p-0"><div className="flex items-start justify-between bg-slate-50 p-5"><div className="flex items-center gap-3"><span className="rounded-xl bg-slate-950 p-2.5 text-orange-400"><Truck className="h-5 w-5" /></span><div><p className="font-mono text-sm font-bold text-slate-900">{unit.unitNumber}</p><p className="text-xs text-slate-500">{unit.type}</p></div></div><Badge className={statusStyles[unit.status]}>{unit.status}</Badge></div><div className="space-y-4 p-5"><div><div className="flex justify-between text-xs"><span className="font-medium text-slate-600">Fuel readiness</span><span className={`font-bold ${unit.fuelPercent < 70 ? "text-red-600" : "text-slate-900"}`}>{unit.fuelPercent}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${unit.fuelPercent < 70 ? "bg-red-500" : unit.fuelPercent < 80 ? "bg-amber-500" : "bg-emerald-500"}`} style={{ width: `${unit.fuelPercent}%` }} /></div></div><div className="grid grid-cols-2 gap-3 text-xs"><div><p className="text-slate-500">Assignment</p><p className="mt-1 font-semibold text-slate-800">{unit.assignment || "Unassigned"}</p></div><div><p className="text-slate-500">Operator</p><p className="mt-1 font-semibold text-slate-800">{unit.operator || "—"}</p></div><div><p className="text-slate-500">Mileage</p><p className="mt-1 font-mono font-semibold text-slate-800">{Number(unit.mileage).toLocaleString()}</p></div><div><p className="text-slate-500">Service due</p><p className="mt-1 font-semibold text-slate-800">{unit.serviceDue || "—"}</p></div></div>{unit.maintenanceNote && <div className="rounded-xl border border-amber-100 bg-amber-50 p-3 text-xs leading-5 text-amber-800">{unit.maintenanceNote}</div>}<Button variant="outline" className="w-full border-slate-200" onClick={() => setEditing(unit)}><Gauge className="mr-2 h-4 w-4" />Update unit</Button></div></CardContent></Card>)}</section>
    <Dialog open={Boolean(editing)} onOpenChange={open => !open && setEditing(null)}><DialogContent><DialogHeader><DialogTitle>Update {editing?.unitNumber}</DialogTitle><DialogDescription>Capture assignment, readiness, and service changes for this unit.</DialogDescription></DialogHeader>{editing && <form className="grid gap-4" onSubmit={event => { event.preventDefault(); const fd = new FormData(event.currentTarget); save.mutate({ id: editing.id, unitNumber: String(fd.get("unitNumber")), type: String(fd.get("type")), status: String(fd.get("status")) as any, fuelPercent: Number(fd.get("fuelPercent")), mileage: Number(fd.get("mileage")), assignment: String(fd.get("assignment") || ""), operator: String(fd.get("operator") || ""), lastService: String(fd.get("lastService") || ""), serviceDue: String(fd.get("serviceDue") || ""), maintenanceNote: String(fd.get("maintenanceNote") || "") }); }}><div className="grid grid-cols-2 gap-3"><div><Label>Unit</Label><Input name="unitNumber" defaultValue={editing.unitNumber} /></div><div><Label>Type</Label><Input name="type" defaultValue={editing.type} /></div></div><div><Label>Status</Label><Select name="status" defaultValue={editing.status}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["operational", "maintenance", "alert", "offline"].map(status => <SelectItem key={status} value={status}>{status}</SelectItem>)}</SelectContent></Select></div><div className="grid grid-cols-2 gap-3"><div><Label>Fuel percentage</Label><Input name="fuelPercent" type="number" min="0" max="100" defaultValue={editing.fuelPercent} /></div><div><Label>Mileage</Label><Input name="mileage" type="number" defaultValue={editing.mileage} /></div></div><div className="grid grid-cols-2 gap-3"><div><Label>Assignment</Label><Input name="assignment" defaultValue={editing.assignment || ""} /></div><div><Label>Operator</Label><Input name="operator" defaultValue={editing.operator || ""} /></div></div><div className="grid grid-cols-2 gap-3"><div><Label>Last service</Label><Input name="lastService" defaultValue={editing.lastService || ""} /></div><div><Label>Service due</Label><Input name="serviceDue" defaultValue={editing.serviceDue || ""} /></div></div><div><Label>Maintenance / readiness note</Label><Textarea name="maintenanceNote" defaultValue={editing.maintenanceNote || ""} /></div><Button disabled={save.isPending} className="bg-orange-500 hover:bg-orange-600">{save.isPending ? "Saving…" : "Save unit update"}</Button></form>}</DialogContent></Dialog>
  </div></DashboardLayout>;
}
