import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, Building2, Pencil, Plus, Package, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { toast } from "sonner";

type Tab = "sites" | "crew" | "materials" | "alerts";
type RecordItem = Record<string, any>;

function SectionTitle({ icon: Icon, title, description }: { icon: any; title: string; description: string }) {
  return <div className="flex items-start gap-3"><span className="rounded-xl bg-orange-100 p-2.5 text-orange-600"><Icon className="h-5 w-5" /></span><div><h2 className="text-lg font-bold text-slate-900">{title}</h2><p className="text-sm text-slate-500">{description}</p></div></div>;
}

function StatusTag({ value }: { value: string }) {
  const colors: Record<string, string> = { active: "bg-emerald-100 text-emerald-700", scheduled: "bg-blue-100 text-blue-700", standby: "bg-amber-100 text-amber-700", on_hold: "bg-red-100 text-red-700", assigned: "bg-orange-100 text-orange-700", available: "bg-emerald-100 text-emerald-700", critical: "bg-red-100 text-red-700", warning: "bg-amber-100 text-amber-700", info: "bg-slate-100 text-slate-600" };
  return <span className={`rounded-full px-2 py-1 text-[10px] font-bold capitalize ${colors[value] || "bg-slate-100 text-slate-600"}`}>{value.replace("_", " ")}</span>;
}

export default function OperationsManager() {
  const [location, setLocation] = useLocation();
  const tabFromUrl = (new URLSearchParams(window.location.search).get("tab") || "sites") as Tab;
  const [tab, setTab] = useState<Tab>(["sites", "crew", "materials", "alerts"].includes(tabFromUrl) ? tabFromUrl : "sites");
  const [editing, setEditing] = useState<{ type: Tab; item?: RecordItem } | null>(null);
  const [auditAlert, setAuditAlert] = useState<RecordItem | null>(null);
  const utils = trpc.useUtils();
  const sites = trpc.aac.jobSites.useQuery();
  const crew = trpc.aac.crew.useQuery();
  const materials = trpc.aac.materials.useQuery();
  const alerts = trpc.aac.alerts.useQuery();
  const alertHistory = trpc.aac.alertHistory.useQuery({ alertId: auditAlert?.id ?? 0 }, { enabled: Boolean(auditAlert?.id) });
  const refresh = () => Promise.all([utils.aac.dashboard.invalidate(), utils.aac.jobSites.invalidate(), utils.aac.crew.invalidate(), utils.aac.materials.invalidate(), utils.aac.alerts.invalidate(), utils.aac.alertHistory.invalidate()]);
  const saveSite = trpc.aac.saveJobSite.useMutation({ onSuccess: () => { toast.success("Job site saved."); refresh(); setEditing(null); }, onError: () => toast.error("Job site could not be saved.") });
  const saveCrew = trpc.aac.saveCrewMember.useMutation({ onSuccess: () => { toast.success("Crew assignment saved."); refresh(); setEditing(null); }, onError: () => toast.error("Crew assignment could not be saved.") });
  const saveMaterial = trpc.aac.saveMaterial.useMutation({ onSuccess: () => { toast.success("Material record saved."); refresh(); setEditing(null); }, onError: () => toast.error("Material record could not be saved.") });
  const saveAlert = trpc.aac.saveAlert.useMutation({ onSuccess: () => { toast.success("Alert saved."); refresh(); setEditing(null); }, onError: () => toast.error("Alert could not be saved.") });
  const transitionAlert = trpc.aac.transitionAlert.useMutation({ onSuccess: () => { toast.success("Alert state saved with an audit entry."); refresh(); }, onError: () => toast.error("Alert state could not be updated.") });

  useEffect(() => { if (["sites", "crew", "materials", "alerts"].includes(tabFromUrl)) setTab(tabFromUrl); }, [tabFromUrl]);
  const changeTab = (next: string) => { const typed = next as Tab; setTab(typed); setLocation(`/operations?tab=${typed}`); window.history.replaceState(null, "", `/operations?tab=${typed}`); };
  const labels: Record<Tab, { singular: string; title: string; description: string; icon: any }> = { sites: { singular: "job site", title: "Job sites & pour schedules", description: "Maintain live placement schedules and location readiness.", icon: Building2 }, crew: { singular: "crew member", title: "Workforce assignments", description: "Maintain individual roles, shifts, assignments, and availability.", icon: Users }, materials: { singular: "material", title: "Materials & reorder controls", description: "Manage inventory quantities and decision-ready reorder thresholds.", icon: Package }, alerts: { singular: "alert", title: "Active operational alerts", description: "Create, acknowledge, and resolve exceptions that need attention.", icon: AlertTriangle } };
  const current = labels[tab];

  return <DashboardLayout><div className="mx-auto max-w-7xl space-y-6">
    <section className="rounded-3xl bg-slate-950 p-6 text-white sm:p-8"><p className="font-mono text-xs tracking-[0.18em] text-orange-300 uppercase">Operations administration</p><h1 className="mt-2 text-3xl font-extrabold">Manage the working day</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Every update is stored in the AAC operations database and reflected in the dashboard and Daily Operations Brief.</p></section>
    <Tabs value={tab} onValueChange={changeTab} className="space-y-5"><TabsList className="h-auto flex-wrap justify-start gap-1 bg-slate-100 p-1"><TabsTrigger value="sites">Job sites & pours</TabsTrigger><TabsTrigger value="crew">Workforce</TabsTrigger><TabsTrigger value="materials">Materials</TabsTrigger><TabsTrigger value="alerts">Active alerts</TabsTrigger></TabsList>
      <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><SectionTitle icon={current.icon} title={current.title} description={current.description} /><Button className="bg-orange-500 hover:bg-orange-600" onClick={() => setEditing({ type: tab })}><Plus className="mr-2 h-4 w-4" />Add {current.singular}</Button></div>
      <TabsContent value="sites" className="mt-0"><Card className="border-slate-200 shadow-sm"><CardContent className="p-0"><div className="hidden grid-cols-[1.2fr_.6fr_.7fr_.7fr_auto] gap-4 border-b border-slate-100 bg-slate-50 px-5 py-3 text-[10px] font-bold tracking-[0.12em] text-slate-500 uppercase md:grid"><span>Site</span><span>Status</span><span>Pour window</span><span>Volume</span><span /></div>{(sites.data ?? []).map((site: RecordItem) => <div key={site.id || site.code} className="grid gap-3 border-b border-slate-100 p-4 last:border-b-0 md:grid-cols-[1.2fr_.6fr_.7fr_.7fr_auto] md:items-center md:px-5"><div><p className="font-bold text-slate-900">{site.code} · {site.name}</p><p className="mt-1 text-xs text-slate-500">{site.location} · {site.client || "AAC Project"}</p></div><div><StatusTag value={site.status} /></div><div className="text-sm text-slate-700">{site.pourDate || "TBD"}<span className="block text-xs text-slate-500">{site.pourStart || "—"}–{site.pourEnd || "—"}</span></div><p className="font-mono text-sm font-bold text-slate-800">{Number(site.plannedYards).toLocaleString()} yd³</p><Button variant="outline" size="sm" className="border-slate-200" onClick={() => setEditing({ type: "sites", item: site })}><Pencil className="mr-1.5 h-3.5 w-3.5" />Edit</Button></div>)}</CardContent></Card></TabsContent>
      <TabsContent value="crew" className="mt-0"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{(crew.data ?? []).map((member: RecordItem) => <Card key={member.id || member.name} className="border-slate-200 shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between"><div><p className="font-bold text-slate-900">{member.name}</p><p className="mt-1 text-xs text-slate-500">{member.role}</p></div><StatusTag value={member.availability} /></div><div className="mt-5 grid grid-cols-2 gap-3 text-xs"><div><p className="text-slate-500">Assignment</p><p className="mt-1 font-semibold text-slate-800">{member.assignment || "Unassigned"}</p></div><div><p className="text-slate-500">Shift</p><p className="mt-1 font-semibold text-slate-800">{member.shift || "—"}</p></div></div><Button variant="outline" size="sm" className="mt-5 w-full border-slate-200" onClick={() => setEditing({ type: "crew", item: member })}><Pencil className="mr-1.5 h-3.5 w-3.5" />Edit assignment</Button></CardContent></Card>)}</div></TabsContent>
      <TabsContent value="materials" className="mt-0"><Card className="border-slate-200 shadow-sm"><CardContent className="p-0">{(materials.data ?? []).map((material: RecordItem) => { const low = Number(material.quantity) < Number(material.reorderThreshold); return <div key={material.id || material.sku} className="flex flex-col justify-between gap-3 border-b border-slate-100 p-4 last:border-b-0 sm:flex-row sm:items-center sm:px-5"><div><p className="font-bold text-slate-900">{material.name}</p><p className="mt-1 text-xs text-slate-500">{material.sku} · {material.supplier || "No supplier"}</p></div><div className="flex items-center gap-6"><div className="text-right"><p className={low ? "font-mono text-sm font-bold text-red-600" : "font-mono text-sm font-bold text-emerald-700"}>{material.quantity} {material.unit}</p><p className="text-[10px] text-slate-500">reorder at {material.reorderThreshold} {material.unit}</p></div><Button variant="outline" size="sm" className="border-slate-200" onClick={() => setEditing({ type: "materials", item: material })}><Pencil className="mr-1.5 h-3.5 w-3.5" />Edit</Button></div></div> })}</CardContent></Card></TabsContent>
      <TabsContent value="alerts" className="mt-0"><div className="grid gap-4 lg:grid-cols-2">{(alerts.data ?? []).map((alert: RecordItem) => <Card key={alert.id || alert.title} className="border-slate-200 shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><AlertTriangle className={`h-4 w-4 ${alert.severity === "critical" ? "text-red-600" : "text-amber-500"}`} /><p className="font-bold text-slate-900">{alert.title}</p></div><p className="mt-2 text-sm leading-6 text-slate-600">{alert.detail}</p><p className="mt-3 text-xs font-semibold text-slate-500">{alert.source}</p></div><StatusTag value={alert.severity} /></div><div className="mt-5 flex flex-wrap gap-2"><Button variant="outline" size="sm" className="border-slate-200" onClick={() => setEditing({ type: "alerts", item: alert })}><Pencil className="mr-1.5 h-3.5 w-3.5" />Edit alert</Button><Button size="sm" variant="outline" className="border-slate-200" onClick={() => setAuditAlert(alert)}>View audit</Button><Button size="sm" variant="outline" className="border-amber-200 text-amber-700 hover:bg-amber-50" disabled={transitionAlert.isPending} onClick={() => transitionAlert.mutate({ alertId: alert.id, status: "acknowledged", note: "Acknowledged from AAC Operations Manager", actor: "AAC Operations" })}>Acknowledge</Button><Button size="sm" className="bg-emerald-600 hover:bg-emerald-700" disabled={transitionAlert.isPending} onClick={() => transitionAlert.mutate({ alertId: alert.id, status: "resolved", note: "Resolved from AAC Operations Manager", actor: "AAC Operations" })}>Resolve</Button></div></CardContent></Card>)}</div></TabsContent>
    </Tabs>
    <Dialog open={Boolean(editing)} onOpenChange={open => !open && setEditing(null)}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{editing?.item ? "Update" : "Add"} {editing ? labels[editing.type].singular : "record"}</DialogTitle><DialogDescription>Changes save to the live operations data used by the dashboard and briefing workspace.</DialogDescription></DialogHeader>{editing?.type === "sites" && <SiteForm initial={editing.item} pending={saveSite.isPending} onSubmit={input => saveSite.mutate(input)} />}{editing?.type === "crew" && <CrewForm initial={editing.item} pending={saveCrew.isPending} onSubmit={input => saveCrew.mutate(input)} />}{editing?.type === "materials" && <MaterialForm initial={editing.item} pending={saveMaterial.isPending} onSubmit={input => saveMaterial.mutate(input)} />}{editing?.type === "alerts" && <AlertForm initial={editing.item} pending={saveAlert.isPending} onSubmit={input => saveAlert.mutate(input)} />}</DialogContent></Dialog>
    <Dialog open={Boolean(auditAlert)} onOpenChange={open => !open && setAuditAlert(null)}><DialogContent><DialogHeader><DialogTitle>Alert audit trail</DialogTitle><DialogDescription>{auditAlert?.title} — immutable state transitions recorded from AAC operations workflows.</DialogDescription></DialogHeader><div className="max-h-72 space-y-3 overflow-y-auto">{alertHistory.isLoading ? <p className="text-sm text-slate-500">Loading audit entries…</p> : (alertHistory.data ?? []).length ? alertHistory.data?.map((entry: any) => <div key={entry.id} className="rounded-xl border border-slate-100 p-3"><div className="flex items-center justify-between"><p className="text-sm font-bold capitalize text-slate-900">{entry.action}</p><p className="text-[10px] text-slate-500">{new Date(entry.createdAt).toLocaleString()}</p></div><p className="mt-1 text-xs leading-5 text-slate-600">{entry.note}</p><p className="mt-2 text-[10px] font-semibold text-slate-500">{entry.actor || "AAC Operations"}</p></div>) : <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No recorded transitions yet for this alert.</p>}</div></DialogContent></Dialog>
  </div></DashboardLayout>;
}

function SiteForm({ initial, pending, onSubmit }: { initial?: RecordItem; pending: boolean; onSubmit: (input: any) => void }) { return <form className="grid gap-4" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); onSubmit({ id: initial?.id, code: String(form.get("code")), name: String(form.get("name")), client: String(form.get("client") || ""), location: String(form.get("location")), status: String(form.get("status")), pourDate: String(form.get("pourDate") || ""), pourStart: String(form.get("pourStart") || ""), pourEnd: String(form.get("pourEnd") || ""), plannedYards: Number(form.get("plannedYards")), notes: String(form.get("notes") || "") }); }}><div className="grid grid-cols-2 gap-3"><Field label="Site code"><Input name="code" defaultValue={initial?.code} placeholder="JS-005" required /></Field><Field label="Status"><Select name="status" defaultValue={initial?.status || "scheduled"}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["scheduled", "active", "standby", "on_hold", "complete"].map(value => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></Field></div><Field label="Project name"><Input name="name" defaultValue={initial?.name} required /></Field><div className="grid grid-cols-2 gap-3"><Field label="Client"><Input name="client" defaultValue={initial?.client || ""} /></Field><Field label="Planned cubic yards"><Input name="plannedYards" type="number" min="0" defaultValue={initial?.plannedYards ?? ""} required /></Field></div><Field label="Location"><Input name="location" defaultValue={initial?.location} required /></Field><div className="grid grid-cols-3 gap-3"><Field label="Pour date"><Input name="pourDate" defaultValue={initial?.pourDate || ""} /></Field><Field label="Start"><Input name="pourStart" defaultValue={initial?.pourStart || ""} /></Field><Field label="End"><Input name="pourEnd" defaultValue={initial?.pourEnd || ""} /></Field></div><Field label="Notes"><Textarea name="notes" defaultValue={initial?.notes || ""} /></Field><Button disabled={pending} className="bg-orange-500 hover:bg-orange-600">{pending ? "Saving…" : "Save job site"}</Button></form>; }
function CrewForm({ initial, pending, onSubmit }: { initial?: RecordItem; pending: boolean; onSubmit: (input: any) => void }) { return <form className="grid gap-4" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); onSubmit({ id: initial?.id, name: String(form.get("name")), role: String(form.get("role")), availability: String(form.get("availability")), assignment: String(form.get("assignment") || ""), shift: String(form.get("shift") || ""), phone: String(form.get("phone") || "") }); }}><Field label="Name"><Input name="name" defaultValue={initial?.name} required /></Field><div className="grid grid-cols-2 gap-3"><Field label="Role"><Input name="role" defaultValue={initial?.role} required /></Field><Field label="Availability"><Select name="availability" defaultValue={initial?.availability || "available"}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["assigned", "available", "off", "unavailable"].map(value => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></Field></div><div className="grid grid-cols-2 gap-3"><Field label="Assignment"><Input name="assignment" defaultValue={initial?.assignment || ""} /></Field><Field label="Shift"><Input name="shift" defaultValue={initial?.shift || ""} /></Field></div><Field label="Phone"><Input name="phone" defaultValue={initial?.phone || ""} /></Field><Button disabled={pending} className="bg-orange-500 hover:bg-orange-600">{pending ? "Saving…" : "Save crew member"}</Button></form>; }
function MaterialForm({ initial, pending, onSubmit }: { initial?: RecordItem; pending: boolean; onSubmit: (input: any) => void }) { return <form className="grid gap-4" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); onSubmit({ id: initial?.id, sku: String(form.get("sku")), name: String(form.get("name")), unit: String(form.get("unit")), quantity: String(form.get("quantity")), reorderThreshold: String(form.get("reorderThreshold")), supplier: String(form.get("supplier") || "") }); }}><div className="grid grid-cols-2 gap-3"><Field label="SKU"><Input name="sku" defaultValue={initial?.sku} required /></Field><Field label="Unit"><Input name="unit" defaultValue={initial?.unit} placeholder="tons" required /></Field></div><Field label="Material name"><Input name="name" defaultValue={initial?.name} required /></Field><div className="grid grid-cols-2 gap-3"><Field label="Current quantity"><Input name="quantity" defaultValue={initial?.quantity} required /></Field><Field label="Reorder threshold"><Input name="reorderThreshold" defaultValue={initial?.reorderThreshold} required /></Field></div><Field label="Supplier"><Input name="supplier" defaultValue={initial?.supplier || ""} /></Field><Button disabled={pending} className="bg-orange-500 hover:bg-orange-600">{pending ? "Saving…" : "Save material"}</Button></form>; }
function AlertForm({ initial, pending, onSubmit }: { initial?: RecordItem; pending: boolean; onSubmit: (input: any) => void }) { return <form className="grid gap-4" onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); onSubmit({ id: initial?.id, title: String(form.get("title")), severity: String(form.get("severity")), source: String(form.get("source")), detail: String(form.get("detail")), status: String(form.get("status")) }); }}><Field label="Alert title"><Input name="title" defaultValue={initial?.title} required /></Field><div className="grid grid-cols-2 gap-3"><Field label="Severity"><Select name="severity" defaultValue={initial?.severity || "warning"}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["critical", "warning", "info"].map(value => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></Field><Field label="Status"><Select name="status" defaultValue={initial?.status || "active"}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["active", "acknowledged", "resolved"].map(value => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></Field></div><Field label="Source"><Input name="source" defaultValue={initial?.source} required /></Field><Field label="Operational detail"><Textarea name="detail" defaultValue={initial?.detail} required /></Field><Button disabled={pending} className="bg-orange-500 hover:bg-orange-600">{pending ? "Saving…" : "Save alert"}</Button></form>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="grid gap-1.5"><Label>{label}</Label>{children}</div>; }
