/**
 * DOGE-LANDSCAPER — GitHub Mission Log Export Hook
 * Pushes Markdown daily reports to JacksonJoshuab/DOGE-Spatial-Explorer
 * Uses GitHub Contents API (requires a PAT with repo write scope)
 * Token is entered by the user in the UI and stored in localStorage (persists across sessions)
 */

import { useState, useCallback } from "react";
import type { RobotPersona } from "@/lib/data";

const REPO_OWNER = "JacksonJoshuab";
const REPO_NAME = "DOGE-Spatial-Explorer";
const LOGS_PATH = "mission-logs";

export interface MissionLogEntry {
  date: string;
  persona: RobotPersona;
  completedTaskIds: string[];
  isSprayActive: boolean;
  windSpeed: number;
  temperature: number;
  humidity: number;
  weatherCondition: string;
  zonesCompleted: string[];
  productsUsed: string[];
  notes: string;
}

export interface GitHubExportState {
  status: "idle" | "pushing" | "success" | "error";
  message: string;
  commitUrl: string | null;
  hasToken: boolean;
}

function generateMarkdown(entry: MissionLogEntry): string {
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" });
  const timeStr = now.toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit", timeZoneName: "short" });

  const taskMap: Record<string, string> = {
    "task-1": "Morning Yard Survey",
    "task-2": "Apply Scotts Weed & Feed",
    "task-3": "Mow Main Lawn",
    "task-4": "Edge Garden Beds",
    "task-5": "Inspect Irrigation",
    "task-6": "Evening Perimeter Check",
  };

  const completedNames = entry.completedTaskIds.map(id => taskMap[id] ?? id);
  const completionRate = Math.round((entry.completedTaskIds.length / 6) * 100);
  const sprayStatus = entry.isSprayActive ? "✅ Active during report" : "⏸ Inactive at report time";
  const windStatus = entry.windSpeed > 10 ? `⚠️ ${entry.windSpeed.toFixed(0)} mph (spray locked)` : `✅ ${entry.windSpeed.toFixed(0)} mph (safe)`;

  return `# 🌱 DOGE-Landscaper Mission Log
## ${dateStr}

> **Robot:** ${entry.persona.name} | **Location:** Wilton, Iowa 52776 (Zone 5b)  
> **Generated:** ${timeStr} | **Version:** v2.7 | **Platform:** Nvidia Jetson Orin AGX

---

## 📊 Mission Summary

| Metric | Value |
|--------|-------|
| Tasks Completed | ${entry.completedTaskIds.length} / 6 (${completionRate}%) |
| Zones Treated | ${entry.zonesCompleted.join(", ") || "None"} |
| Spray Status | ${sprayStatus} |
| Wind Condition | ${windStatus} |
| Products Used | ${entry.productsUsed.join(", ") || "None"} |

---

## 🌤️ Weather Conditions at Application

| Parameter | Value |
|-----------|-------|
| Temperature | ${entry.temperature}°F |
| Humidity | ${entry.humidity}% |
| Wind Speed | ${entry.windSpeed.toFixed(0)} mph |
| Condition | ${entry.weatherCondition} |
| Spray Window | ${entry.windSpeed <= 10 ? "✅ Optimal" : entry.windSpeed <= 15 ? "⚠️ Acceptable" : "🚫 Locked"} |

---

## ✅ Completed Tasks

${completedNames.length > 0
    ? completedNames.map(t => `- [x] ${t}`).join("\n")
    : "- [ ] No tasks completed this session"}

${entry.completedTaskIds.length < 6
    ? "\n### Pending Tasks\n" + Object.entries(taskMap)
        .filter(([id]) => !entry.completedTaskIds.includes(id))
        .map(([, name]) => `- [ ] ${name}`)
        .join("\n")
    : ""}

---

## 🧪 Products Applied

${entry.productsUsed.length > 0
    ? entry.productsUsed.map(p => `### ${p}\n- Applied per label instructions\n- Minimum overspray protocol active\n- Wind guard deployed near garden beds`).join("\n\n")
    : "_No products applied this session._"}

---

## 🗺️ Zone Status

| Zone | Status | Notes |
|------|--------|-------|
| Zone A (Front Lawn) | ${entry.zonesCompleted.includes("A") ? "✅ Treated" : "⏳ Pending"} | Near oak tree — avoid root zone |
| Zone B (Side Yard) | ${entry.zonesCompleted.includes("B") ? "✅ Treated" : "⏳ Pending"} | Swing set area — child-safe buffer |
| Zone C (Garden Beds) | ${entry.zonesCompleted.includes("C") ? "✅ Treated" : "⏳ Pending"} | Scilla bulbs present — selective spray |
| Zone D (Back Fence) | ${entry.zonesCompleted.includes("D") ? "✅ Treated" : "⏳ Pending"} | Orange safety fence boundary |

---

## 🤖 Chip's Notes

> *"${entry.notes}"*
> 
> — ${entry.persona.name}, ${entry.persona.tagline}

---

## 🛠️ System Info

\`\`\`
Robot Platform : Nvidia Jetson Orin AGX
AI Framework   : NVIDIA Isaac ROS + CoreML
Camera         : Continuity Camera (iPhone 17 Pro Max)
LiDAR          : Apple LiDAR Scanner (905-Backyard scan)
Location       : 41.5867°N, 91.0154°W
Firmware       : DOGE-Landscaper v2.7
\`\`\`

---

*Auto-generated by DOGE-Landscaper · [dogelandscap-cao3qxuu.manus.space](https://dogelandscap-cao3qxuu.manus.space)*
`;
}

export function useGitHubExport() {
  const [state, setState] = useState<GitHubExportState>({
    status: "idle",
    message: "",
    commitUrl: null,
    hasToken: !!localStorage.getItem("gh_pat"),
  });

  const setToken = useCallback((token: string) => {
    if (token.trim()) {
      localStorage.setItem("gh_pat", token.trim());
      setState(s => ({ ...s, hasToken: true, message: "Token saved to localStorage (persists across sessions)" }));
    }
  }, []);

  const clearToken = useCallback(() => {
    localStorage.removeItem("gh_pat");
    setState(s => ({ ...s, hasToken: false, message: "" }));
  }, []);

  const exportToGitHub = useCallback(async (entry: MissionLogEntry) => {
    const token = localStorage.getItem("gh_pat");
    if (!token) {
      setState(s => ({ ...s, status: "error", message: "No GitHub token — enter your PAT first" }));
      return;
    }

    setState({ status: "pushing", message: "Generating Markdown report...", commitUrl: null, hasToken: true });

    try {
      const markdown = generateMarkdown(entry);
      const now = new Date();
      const dateSlug = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${String(now.getDate()).padStart(2, "0")}`;
      const timeSlug = `${String(now.getHours()).padStart(2, "0")}${String(now.getMinutes()).padStart(2, "0")}`;
      const filename = `${LOGS_PATH}/${dateSlug}-${timeSlug}-chip-mission.md`;
      const content = btoa(unescape(encodeURIComponent(markdown)));

      setState(s => ({ ...s, message: `Pushing to ${REPO_OWNER}/${REPO_NAME}...` }));

      // Check if file exists (to get SHA for update)
      let sha: string | undefined;
      try {
        const checkRes = await fetch(
          `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/contents/${filename}`,
          { headers: { Authorization: `Bearer ${token}`, Accept: "application/vnd.github+json" } }
        );
        if (checkRes.ok) {
          const existing = await checkRes.json();
          sha = existing.sha;
        }
      } catch { /* file doesn't exist yet — that's fine */ }

      const body: Record<string, string> = {
        message: `🌱 Mission log: ${dateSlug} — ${entry.completedTaskIds.length}/6 tasks · ${entry.persona.name}`,
        content,
        branch: "main",
      };
      if (sha) body.sha = sha;

      const res = await fetch(
        `https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/contents/${filename}`,
        {
          method: "PUT",
          headers: {
            Authorization: `Bearer ${token}`,
            Accept: "application/vnd.github+json",
            "Content-Type": "application/json",
          },
          body: JSON.stringify(body),
        }
      );

      if (!res.ok) {
        const err = await res.json();
        throw new Error(err.message ?? `HTTP ${res.status}`);
      }

      const result = await res.json();
      const commitUrl = result.commit?.html_url ?? `https://github.com/${REPO_OWNER}/${REPO_NAME}/blob/main/${filename}`;

      setState({
        status: "success",
        message: `✅ Pushed to ${REPO_NAME}!`,
        commitUrl,
        hasToken: true,
      });

      // Reset to idle after 8 seconds
      setTimeout(() => setState(s => ({ ...s, status: "idle", message: "" })), 8000);

    } catch (err) {
      const msg = err instanceof Error ? err.message : "Unknown error";
      setState({ status: "error", message: `Push failed: ${msg}`, commitUrl: null, hasToken: true });
      setTimeout(() => setState(s => ({ ...s, status: "idle" })), 6000);
    }
  }, []);

  return { state, setToken, clearToken, exportToGitHub };
}
