const VERSION='gonzo-health-experience/2.3.0';
const app=document.querySelector('#app');
const $=(s,r=app)=>r?.querySelector(s);const $$=(s,r=app)=>[...(r?.querySelectorAll(s)||[])];
const state={lastView:'',start:0};
function addSkip(){if(document.querySelector('.gh-skip'))return;const a=document.createElement('a');a.className='gh-skip';a.href='#app';a.textContent='Skip to activity';document.body.prepend(a)}
function annotateBattery(){const defs={daily:['3 min','36 responses','Quick baseline'],standard:['15 min','132 responses','Deeper profile'],research:['30–45 min','252 responses','Research depth']};$$('[data-battery]').forEach(c=>{if(c.querySelector('.gh-exam-meta'))return;const d=defs[c.dataset.battery];if(!d)return;const m=document.createElement('div');m.className='gh-exam-meta';m.innerHTML=d.map(x=>`<span>${x}</span>`).join('');c.append(m)})}
function addReadiness(){const hero=$('.hero,.hero-stage');if(!hero||$('.gh-readiness'))return;const n=document.createElement('aside');n.className='gh-readiness';n.innerHTML='<strong>Before you begin</strong><span>Quiet space</span><span>Comfortable viewing distance</span><span>Use your normal input method</span><span>Accuracy before speed</span>';hero.insertAdjacentElement('afterend',n)}
function enhanceTest(){const stage=$('.stage,.test-stage');if(!stage)return;document.body.dataset.ghExam='active';if(!$('.gh-session-guide')){const g=document.createElement('div');g.className='gh-session-guide';g.innerHTML='<span><b>1</b> Understand</span><span><b>2</b> Respond</span><span><b>3</b> Recover</span><span><b>4</b> Review</span>';stage.parentElement?.insertBefore(g,stage)}const progress=$('[role="progressbar"],.progress');if(progress)progress.setAttribute('aria-label','Assessment progress');$$('button',stage).forEach(b=>{if(!b.getAttribute('aria-label'))b.setAttribute('aria-label',b.textContent.trim()||'Response option')})}
function enhanceResults(){const root=$('.results,.results-view,[data-view="results"]');if(!root||root.dataset.ghReport===VERSION)return;root.dataset.ghReport=VERSION;const score=root.querySelector('.score,.score-ring,.hero-score');const section=document.createElement('section');section.className='gh-report-explainer';section.innerHTML='<div><span class="eyebrow">How to read this</span><h2>One session is a snapshot, not a diagnosis.</h2><p>Prioritize validity and accuracy first, then response speed and consistency. Trends become more useful after repeated comparable sessions.</p></div><div class="gh-report-legend"><span><i class="good"></i>Stable strength</span><span><i class="watch"></i>Worth watching</span><span><i class="caution"></i>Use caution</span></div>';if(score)score.insertAdjacentElement('afterend',section);else root.prepend(section);if(!root.querySelector('.gh-next-actions')){const next=document.createElement('section');next.className='gh-next-actions';next.innerHTML='<h3>Recommended next steps</h3><div><button type="button" data-gh-repeat>Repeat comparable check</button><button type="button" data-gh-history>Review trend</button><button type="button" data-gh-export>Export evidence</button></div><small>Goals should include a metric, baseline, target, timeframe, and guardrail.</small>';root.append(next);next.querySelector('[data-gh-repeat]')?.addEventListener('click',()=>location.href='./?battery=daily');next.querySelector('[data-gh-history]')?.addEventListener('click',()=>location.href='./?results=history');next.querySelector('[data-gh-export]')?.addEventListener('click',()=>app.querySelector('[data-action="export"],button[title*="Export"]')?.click())}}
function addReportNav(){const nav=$('nav');if(!nav||nav.querySelector('[data-gh-report-help]'))return;const b=document.createElement('button');b.type='button';b.dataset.ghReportHelp='';b.textContent='How scoring works';b.addEventListener('click',()=>{const el=$('.gh-report-explainer,.anchor-panel,.anchor-bridge');el?.scrollIntoView({behavior:'smooth',block:'center'})});nav.append(b)}
function keyboard(){document.addEventListener('keydown',e=>{if(e.key==='Escape'){const stop=$('[data-action="stop"],button[title*="Stop"]');if(stop&&document.body.dataset.ghExam==='active')stop.focus()}if((e.metaKey||e.ctrlKey)&&e.key==='Enter')$('[data-action="start"]')?.click()},{once:true})}
function classify(){const text=app?.textContent||'';if(/results|performance profile|validity/i.test(text))return'results';if(/pause|stop|trial|response/i.test(text)&&$('.stage,.test-stage'))return'test';return'lobby'}
function enhance(){if(!app||app.hidden)return;addSkip();annotateBattery();addReadiness();addReportNav();const view=classify();if(view==='test')enhanceTest();if(view==='results')enhanceResults();state.lastView=view;document.documentElement.dataset.ghExperience=VERSION}
let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;enhance()})}).observe(app,{subtree:true,childList:true});keyboard();enhance();window.__GONZO_HEALTH_EXPERIENCE__=Object.freeze({version:VERSION,examExpanded:true,reportingExpanded:true});