#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { webkit } from 'playwright';

const ROOT=new URL((process.env.GH_BASE_URL||'https://127.0.0.1:4173/').replace(/\/?$/,'/'));
const SITE=path.resolve(process.env.GH_SITE_DIR||'gonzo-health-spatial-cognition');
const OUT=path.resolve(process.env.GH_OUTPUT_DIR||'evaluation-output/gonzo-health-ux-v2');
const EXPERIENCE='gonzo-health-experience/2.3.1';
const checks=[];const browserErrors=[];const screenshots=[];let fatal=null;
const add=(id,domain,points,passed,detail,critical=false)=>checks.push({id,domain,points,earned:passed?points:0,passed:!!passed,critical,detail:String(detail)});
const read=file=>fs.readFile(path.join(SITE,file),'utf8');
const shot=async(page,name)=>{const target=path.join(OUT,'screenshots',name);await page.screenshot({path:target,fullPage:true});screenshots.push(target)};
const visible=async locator=>(await locator.count())>0&&await locator.first().isVisible();
function monitor(page,label,offline){page.on('console',message=>{if(['error','assert'].includes(message.type()))browserErrors.push(`${label}: console ${message.text()}`)});page.on('pageerror',error=>browserErrors.push(`${label}: page ${error.message}`));page.on('response',response=>{if(!offline.value&&response.status()>=400)browserErrors.push(`${label}: HTTP ${response.status()} ${response.url()}`)});page.on('requestfailed',request=>{if(!offline.value)browserErrors.push(`${label}: request ${request.url()} ${request.failure()?.errorText||''}`)})}
async function waitApp(page){await page.waitForSelector('#app:not([hidden])',{timeout:35000});await page.waitForFunction(expected=>window.__GONZO_HEALTH_EXPERIENCE__?.version===expected,EXPERIENCE,{timeout:20000})}
async function press(page,locator){await locator.waitFor({state:'visible',timeout:15000});await locator.focus();await page.keyboard.press('Enter')}
async function dimensions(page,selector){return page.locator(selector).evaluateAll(nodes=>nodes.filter(node=>{const style=getComputedStyle(node);return style.display!=='none'&&style.visibility!=='hidden'&&node.getClientRects().length>0}).map(node=>{const rect=node.getBoundingClientRect();return{width:rect.width,height:rect.height,label:node.getAttribute('aria-label')||node.textContent?.trim()||''}}))}
async function chooseConsent(page){const modal=page.locator('#consent-modal');if(!(await modal.count()))return;await modal.waitFor({state:'visible',timeout:10000});const checkbox=modal.locator('input[type="checkbox"]').first();if(await checkbox.count()){await checkbox.focus();if(!(await checkbox.isChecked()))await page.keyboard.press('Space')}const buttons=modal.getByRole('button');let chosen=null;for(let i=0;i<await buttons.count();i++){const button=buttons.nth(i);const name=((await button.getAttribute('aria-label'))||await button.textContent()||'').trim();if(/continue|agree|begin|start|proceed/i.test(name)&&!/cancel|back|close|stop/i.test(name))chosen=button}if(!chosen)throw new Error('Consent modal has no affirmative continuation control.');await press(page,chosen);await modal.waitFor({state:'hidden',timeout:15000})}

await fs.mkdir(path.join(OUT,'screenshots'),{recursive:true});
const required=['index.html','boot.mjs','brand-refresh.mjs','brand-refresh.css','light-theme.css','experience-v2.mjs','experience-v2.css','experience-state.css','manifest.webmanifest','service-worker.js','healthcheck.json','privacy.html','support.html'];
const source=Object.fromEntries(await Promise.all(required.map(async file=>[file,await read(file)])));
const health=JSON.parse(source['healthcheck.json']);const manifest=JSON.parse(source['manifest.webmanifest']);const combined=Object.values(source).join('\n');const payloadCount=new Set(source['service-worker.js'].match(/payload\/g\d{2}\/\d{3}\.txt/g)||[]).size;
add('contract.responses-anchors','exam',10,JSON.stringify(health.batteryResponseCounts)===JSON.stringify([36,132,252])&&health.sharedAnchors===12,'The release retains 36/132/252 responses and 12 shared anchors.',true);
add('contract.presentation-only','exam',5,/MutationObserver/.test(source['experience-v2.mjs'])&&!/(scoreSession|generateBattery|ScoringEngine|evaluateAdaptiveWindow|measurementModelVersion\s*=|validity\s*=)/.test(source['experience-v2.mjs']),'The experience layer remains presentation-only.',true);
add('pwa.assets','pwa',5,payloadCount===48&&['experience-v2.mjs','experience-v2.css','experience-state.css','index.html','offline.html'].every(file=>source['service-worker.js'].includes(file)),`Offline cache includes ${payloadCount}/48 payload chunks and every UX shell asset.`,true);
add('privacy.boundary','privacy',5,!/(OPENAI_API_KEY|sk-proj-|sk-[A-Za-z0-9_-]{32,}|google-analytics|mixpanel|amplitude\.com|segment\.com)/i.test(combined)&&/private-by-default|local-first|local by default/i.test(combined)&&/not a diagnosis|non-diagnostic/i.test(combined),'No public provider secret/tracker marker; local-first and non-diagnostic boundaries remain.',true);

let browser;
try{
 browser=await webkit.launch({headless:true});
 const audits=[];
 for(const spec of [{name:'phone',viewport:{width:390,height:844},motion:'no-preference'},{name:'tablet',viewport:{width:768,height:1024},motion:'reduce'},{name:'desktop',viewport:{width:1440,height:1000},motion:'no-preference'}]){
  const context=await browser.newContext({viewport:spec.viewport,reducedMotion:spec.motion,serviceWorkers:'allow'});const page=await context.newPage();const offline={value:false};monitor(page,spec.name,offline);const response=await page.goto(ROOT.href,{waitUntil:'domcontentloaded',timeout:45000});await waitApp(page);
  const base=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,theme:document.documentElement.dataset.theme,generations:document.querySelectorAll('[data-generation]').length,batteries:document.querySelectorAll('[data-battery]').length,examMeta:document.querySelectorAll('.gh-exam-meta').length,readiness:!!document.querySelector('.gh-readiness'),reduced:matchMedia('(prefers-reduced-motion: reduce)').matches}));
  const targets=await dimensions(page,'[data-generation],[data-battery],[data-action="start"],[data-action="demo"],.gh-theme-toggle');const targetPass=targets.length>=8&&targets.every(target=>target.width>=42&&target.height>=42);await shot(page,`${spec.name}-lobby.png`);
  await page.evaluate(()=>document.documentElement.dataset.contrast='high');const contrast=await page.locator('.glass,.topbar').first().evaluate(element=>{const style=getComputedStyle(element);return{background:style.backgroundColor,backdrop:style.backdropFilter||style.webkitBackdropFilter||'none'}});const contrastPass=/rgb\(0, 0, 0\)|rgba\(0, 0, 0, 1\)/.test(contrast.background)&&contrast.backdrop==='none';
  await page.evaluate(()=>{document.documentElement.dataset.contrast='normal';document.documentElement.style.fontSize='200%'});const zoom=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,primary:[...document.querySelectorAll('button')].some(button=>/start daily|18-second demo/i.test(button.textContent||'')&&button.getClientRects().length)}));audits.push({name:spec.name,responseOK:response?.ok(),base,targetPass,contrastPass,zoomPass:zoom.primary&&zoom.scrollWidth<=zoom.clientWidth+32});await context.close();
 }
 add('exam.clarity-runtime','exam',10,audits.every(audit=>audit.responseOK&&audit.base.generations===7&&audit.base.batteries===3&&audit.base.examMeta>=3&&audit.base.readiness),'Phone, tablet, and desktop expose seven themes, three annotated batteries, and readiness guidance.',true);
 add('access.targets-responsive','accessibility',10,audits.every(audit=>audit.targetPass&&audit.base.scrollWidth<=audit.base.clientWidth+32&&audit.zoomPass),audits.map(audit=>`${audit.name}[targets=${audit.targetPass},normal=${audit.base.scrollWidth}/${audit.base.clientWidth},zoom=${audit.zoomPass}]`).join(' '),true);
 add('access.contrast-motion','accessibility',10,audits.every(audit=>audit.contrastPass)&&audits.find(audit=>audit.name==='tablet')?.base.reduced===true,'High contrast is opaque and reduced-motion is active.',true);

 const context=await browser.newContext({viewport:{width:1440,height:1000},serviceWorkers:'allow'});const page=await context.newPage();const offline={value:false};monitor(page,'flow',offline);await page.goto(ROOT.href,{waitUntil:'domcontentloaded',timeout:45000});await waitApp(page);
 const defaultLight=await page.evaluate(()=>document.documentElement.dataset.theme==='light');await press(page,page.locator('[data-gh-theme-toggle]').first());const darkApplied=await page.evaluate(()=>document.documentElement.dataset.theme==='dark'&&localStorage.getItem('gonzo-health-theme')==='dark');await page.reload({waitUntil:'domcontentloaded'});await waitApp(page);const darkPersisted=await page.evaluate(()=>document.documentElement.dataset.theme==='dark');await page.evaluate(()=>localStorage.removeItem('gonzo-health-theme'));await page.reload({waitUntil:'domcontentloaded'});await waitApp(page);add('pwa.theme','pwa',5,defaultLight&&darkApplied&&darkPersisted,'Light is default and a keyboard-selected dark preference persists.');
 await press(page,page.locator('[data-generation="genx"]').first());await press(page,page.locator('[data-battery="daily"]').first());await press(page,page.getByRole('button',{name:/run 18-second demo|watch walkthrough|18-second|\bdemo\b/i}).first());await chooseConsent(page);
 await page.waitForSelector('[data-gh-exam-root]',{timeout:20000});await page.waitForSelector('#gh-session-guide',{timeout:10000});const pause=await visible(page.locator('[data-action="pause"]'));const stop=await visible(page.locator('[data-action="stop"]'));const responses=await dimensions(page,'[data-gh-response]');const responsesOK=responses.length>=4&&responses.every(target=>target.width>=42&&target.height>=42);await shot(page,'desktop-assessment.png');add('exam.keyboard-flow','functionality',15,pause&&stop&&responsesOK,`Timed state marked; pause=${pause}, stop=${stop}, responseTargets=${responses.length}.`,true);
 await page.waitForSelector('[data-gh-report-root]',{timeout:75000});await page.waitForSelector('.gh-report-explainer',{timeout:10000});const report=await page.evaluate(()=>({copy:(document.querySelector('.gh-report-explainer')?.textContent||'').toLowerCase(),next:!!document.querySelector('.gh-next-actions'),repeat:!!document.querySelector('[data-gh-repeat]'),history:!!document.querySelector('[data-gh-history]'),export:!!document.querySelector('[data-gh-export]')}));await shot(page,'desktop-results.png');add('report.validity-first','reporting',10,/snapshot/.test(report.copy)&&/not a diagnosis/.test(report.copy),'Results establish uncertainty and non-diagnostic interpretation before next steps.',true);add('report.next-actions','reporting',5,report.next&&report.repeat&&report.history&&report.export,'Results expose repeat, trend, and export actions.');
 await page.goto(ROOT.href,{waitUntil:'domcontentloaded'});await waitApp(page);await page.waitForFunction(()=>!!navigator.serviceWorker?.controller,null,{timeout:25000}).catch(async()=>{await page.reload({waitUntil:'domcontentloaded'});await waitApp(page);await page.waitForFunction(()=>!!navigator.serviceWorker?.controller,null,{timeout:15000})});offline.value=true;await context.setOffline(true);let offlinePass=false;try{await page.goto(new URL('?battery=daily&audit=offline',ROOT).href,{waitUntil:'domcontentloaded',timeout:20000});await page.waitForSelector('#app:not([hidden])',{timeout:15000});offlinePass=true}catch{}finally{await context.setOffline(false);offline.value=false}add('pwa.offline','pwa',5,offlinePass,'An uncached battery deep link loads from the cached app shell while offline.',true);await context.close();
}catch(error){fatal=error instanceof Error?`${error.name}: ${error.message}`:String(error);add('evaluation.execution','quality',0,false,fatal,true)}finally{if(browser)await browser.close()}
add('quality.browser-errors','quality',5,browserErrors.length===0,browserErrors.length?browserErrors.join(' | '):'No critical browser errors.',true);
const total=checks.reduce((sum,check)=>sum+check.points,0);const earned=checks.reduce((sum,check)=>sum+check.earned,0);const criticalFailures=checks.filter(check=>check.critical&&!check.passed);const score=total?Math.round(earned/total*100):0;const passed=score>=90&&criticalFailures.length===0&&!fatal;const report={schema:'gonzo-health-ux-evaluation/2.2',url:ROOT.href,experience:EXPERIENCE,score,passed,totalPoints:total,earnedPoints:earned,fatal,criticalFailures,checks,browserErrors,screenshots,generatedAt:new Date().toISOString()};await fs.writeFile(path.join(OUT,'report.json'),JSON.stringify(report,null,2));const lines=['# Gonzo | Health UX Evaluation v2','',`**Score: ${score}/100 — ${passed?'PASS':'FAIL'}**`,'',`Critical failures: **${criticalFailures.length}**`,'','| Check | Domain | Score | Critical | Result |','|---|---|---:|:---:|:---:|',...checks.map(check=>`| ${check.id} | ${check.domain} | ${check.earned}/${check.points} | ${check.critical?'Yes':'No'} | ${check.passed?'PASS':'FAIL'} |`),'','## Details',...checks.map(check=>`- **${check.id}:** ${check.detail}`),'','## Browser errors','',browserErrors.length?browserErrors.map(error=>`- ${error}`).join('\n'):'None.',...(fatal?['','## Fatal evaluator error','',fatal]:[])];await fs.writeFile(path.join(OUT,'report.md'),lines.join('\n'));console.log(lines.join('\n'));if(!passed)process.exit(1);
